// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmycduwczvoyrrenbxry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJteWNkdXdjenZveXJyZW5ieHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzkwMTIsImV4cCI6MjA2NzM1NTAxMn0.esrfyktM2eTchUw-6BzQta6QhVabkVZZ0AxzSy-qkLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});